name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every week
    - cron: "0 */168 * * *"

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@V3

          
