name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every week
    - cron: "0 0 * * 0"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: "░▒▓█" # Use a single block character to disable the graph
          TIME_RANGE: all_time # Display all-time stats
          LANG_COUNT: 10 # Display 10 languages
          SHOW_TIME: false # Hide time spent for each language
          SHOW_TOTAL: false # Hide total coding time
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: false # optional
